use Games::Lacuna::Model::Building::BuildingRole;

class Games::Lacuna::Model::Building::Buildings::algae does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::apple does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::atmosphericevaporator does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::bean does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::beeldeban does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::bread does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::burger does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::cheese does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::chip does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::cider does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::cloakinglab does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::corn does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::cornmeal does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::crater does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::dairy does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::denton does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::deployedbleeder does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::energyreserve does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::espionage does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::fission does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::fissure does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::foodreserve does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::fusion does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::gasgiantlab does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::gasgiantplatform does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::geo does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::greatballofjunk does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::grove does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::hydrocarbon does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::junkhengesculpture does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::lagoon does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::lake does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::lapis does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::luxuryhousing does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::malcud does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::metaljunkarches does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::mine does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::munitionslab does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::orerefinery does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::orestorage does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::pancake does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::pie does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::pilottraining does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::propulsion does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::pyramidjunksculpture does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::ravine does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::rockyoutcrop does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::sand does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::saw does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::shake does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::singularity does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::soup does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::spacejunkpark does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::sslb does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::sslc does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::ssld does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::stockpile does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::supplypod does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::syrup does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::terraforminglab does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::terraformingplatform does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::university does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wastedigester does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wasteenergy does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wasteexchanger does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wasterecycling does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wastesequestration does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wastetreatment does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::waterproduction does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::waterpurification does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::waterreclamation does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::waterstorage does Games::Lacuna::Model::Building::BuildingRole {}
class Games::Lacuna::Model::Building::Buildings::wheat does Games::Lacuna::Model::Building::BuildingRole {}

